name: 发布页面

on:
  push:
    branches: [master] # 触发分支
  workflow_dispatch: # 允许手动触发

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 安装 Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 安装依赖
        run: bun install --frozen-lockfile --no-symlinks

      - name: 构建
        run: bun run generate

      - name: 配置 Github Pages
        uses: actions/configure-pages@v3

      - name: 上传项目
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

      # 发布
      - name: 发布
        id: deployment
        uses: actions/deploy-pages@v4
